### ISSUE TITLE
Make the component compatible with SSR

### ISSUE THREAD

**Issue by gtm-nayan** [gtm-nayan/svelte-pdfjs#3]
I thought it was compatible with SSR but that apparently only works in dev mode. 

Build fails with different errors presumably also at different stages depending on what adapter is used

```
> Using @sveltejs/adapter-node
> Cannot find module 'projectdir\node_modules\pdfjs-dist\build\pdf' imported from projectdir\.svelte-kit\output\server\app.js
Did you mean to import pdfjs-dist@2.10.377/node_modules/pdfjs-dist/build/pdf.js?
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'projectdir\node_modules\pdfjs-dist\build\pdf' imported from projectdir\.svelte-kit\output\server\app.js
Did you mean to import pdfjs-dist@2.10.377/node_modules/pdfjs-dist/build/pdf.js?
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:416:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
 ERROR  Command failed with exit code 1.
```

```
> Using @sveltejs/adapter-netlify
 > node_modules/.pnpm/pdfjs-dist@2.10.377/node_modules/pdfjs-dist/build/pdf.js:4452:29: error: Could not resolve "canvas" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    4452 │       const Canvas = require("canvas");
         ╵                              ~~~~~~~~

> Build failed with 1 error:
node_modules/.pnpm/pdfjs-dist@2.10.377/node_modules/pdfjs-dist/build/pdf.js:4452:29: error: Could not resolve "canvas" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
Error: Build failed with 1 error:
node_modules/.pnpm/pdfjs-dist@2.10.377/node_modules/pdfjs-dist/build/pdf.js:4452:29: error: Could not resolve "canvas" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    at failureErrorWithLog (projectdir\node_modules\.pnpm\esbuild@0.13.12\node_modules\esbuild\lib\main.js:1493:15)
    at projectdir\node_modules\.pnpm\esbuild@0.13.12\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (projectdir\node_modules\.pnpm\esbuild@0.13.12\node_modules\esbuild\lib\main.js:1069:65)
    at buildResponseToResult (projectdir\node_modules\.pnpm\esbuild@0.13.12\node_modules\esbuild\lib\main.js:1149:7)
    at projectdir\node_modules\.pnpm\esbuild@0.13.12\node_modules\esbuild\lib\main.js:1258:14
    at projectdir\node_modules\.pnpm\esbuild@0.13.12\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (projectdir\node_modules\.pnpm\esbuild@0.13.12\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (projectdir\node_modules\.pnpm\esbuild@0.13.12\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
 ERROR  Command failed with exit code 1.
```

**Comment by gtm-nayan** [comment]
Done
